print("Hello World!")
print("如果gitbash不能显示中文的话，就设置gitbash的locale为zh_CN，编码设置为GBK")
print("python3对中文的支持比python2好，不用开始的encoding注释了")
print("Hello again")
print("I like typing this.")
print("This is fun.")
print("Yay! Printing.")
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
